### Global ansible-lint configuration (template)
# Place or symlink this into project roots to apply the global defaults.

skip_list:
- "var-naming[pattern]"
- "var-naming[no-role-prefix]"
- "run-once[task]"
- "fqcn[keyword]"

exclude_paths:
- "files/"
- "data/"
- "logs/"
- "stub_data/"
- "collections/"
- ".collections/"
- "test/"
- "venv/"
- ".venv/"
- ".git/"
- "ACT/"
- ".github/"
- ".avd_vars"
- "group_vars/"
- "outputs/"
- "outputs.bak/"
- "playbook_examples/"
- "*.pre-commit-config.yaml*"
