plugins:
  MD013:
    enabled: true
    line_length: 120
    heading_line_length: 90
    code_block_line_length: 120
  MD024:
    enabled: false
  MD025:
    enabled: false
  MD036:
    enabled: false
extensions:
  front-matter:
    enabled: true
